// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type User struct {
	ID         pgtype.UUID        `json:"id"`
	FirstName  pgtype.Text        `json:"first_name"`
	LastName   pgtype.Text        `json:"last_name"`
	Email      string             `json:"email"`
	Username   string             `json:"username"`
	BirthDate  pgtype.Date        `json:"birth_date"`
	Address    string             `json:"address"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdpatedAt pgtype.Timestamptz `json:"updpated_at"`
}
